import { db } from "../index";
import { exerciseLibrary } from "../schema";

// ~100 common exercises, alphabetical, covering all muscle groups
const exercises = [
  { name: "Ab Wheel Rollout",           slug: "ab-wheel-rollout",           muscleGroups: ["core"],                        equipment: "bodyweight", isCompound: false },
  { name: "Arnold Press",               slug: "arnold-press",               muscleGroups: ["shoulders","triceps"],         equipment: "dumbbell",   isCompound: false },
  { name: "Barbell Curl",               slug: "barbell-curl",               muscleGroups: ["biceps"],                      equipment: "barbell",    isCompound: false },
  { name: "Barbell Row",                slug: "barbell-row",                muscleGroups: ["back","biceps"],               equipment: "barbell",    isCompound: true  },
  { name: "Bench Press",                slug: "bench-press",                muscleGroups: ["chest","triceps","shoulders"], equipment: "barbell",    isCompound: true  },
  { name: "Box Jump",                   slug: "box-jump",                   muscleGroups: ["quads","glutes","cardio"],     equipment: "bodyweight", isCompound: true  },
  { name: "Bulgarian Split Squat",      slug: "bulgarian-split-squat",      muscleGroups: ["quads","glutes"],              equipment: "dumbbell",   isCompound: true  },
  { name: "Cable Crossover",            slug: "cable-crossover",            muscleGroups: ["chest"],                       equipment: "cable",      isCompound: false },
  { name: "Cable Crunch",               slug: "cable-crunch",               muscleGroups: ["core"],                        equipment: "cable",      isCompound: false },
  { name: "Cable Curl",                 slug: "cable-curl",                 muscleGroups: ["biceps"],                      equipment: "cable",      isCompound: false },
  { name: "Cable Lateral Raise",        slug: "cable-lateral-raise",        muscleGroups: ["shoulders"],                   equipment: "cable",      isCompound: false },
  { name: "Calf Raise",                 slug: "calf-raise",                 muscleGroups: ["calves"],                      equipment: "machine",    isCompound: false },
  { name: "Chest Fly",                  slug: "chest-fly",                  muscleGroups: ["chest"],                       equipment: "dumbbell",   isCompound: false },
  { name: "Chin-up",                    slug: "chin-up",                    muscleGroups: ["back","biceps"],               equipment: "bodyweight", isCompound: true  },
  { name: "Close Grip Bench Press",     slug: "close-grip-bench-press",     muscleGroups: ["triceps","chest"],             equipment: "barbell",    isCompound: true  },
  { name: "Concentration Curl",         slug: "concentration-curl",         muscleGroups: ["biceps"],                      equipment: "dumbbell",   isCompound: false },
  { name: "Deadlift",                   slug: "deadlift",                   muscleGroups: ["back","hamstrings","glutes"],  equipment: "barbell",    isCompound: true  },
  { name: "Decline Bench Press",        slug: "decline-bench-press",        muscleGroups: ["chest","triceps"],             equipment: "barbell",    isCompound: true  },
  { name: "Dip",                        slug: "dip",                        muscleGroups: ["chest","triceps"],             equipment: "bodyweight", isCompound: true  },
  { name: "Dumbbell Curl",              slug: "dumbbell-curl",              muscleGroups: ["biceps"],                      equipment: "dumbbell",   isCompound: false },
  { name: "Dumbbell Fly",               slug: "dumbbell-fly",               muscleGroups: ["chest"],                       equipment: "dumbbell",   isCompound: false },
  { name: "Dumbbell Press",             slug: "dumbbell-press",             muscleGroups: ["chest","triceps","shoulders"], equipment: "dumbbell",   isCompound: true  },
  { name: "Dumbbell Row",               slug: "dumbbell-row",               muscleGroups: ["back","biceps"],               equipment: "dumbbell",   isCompound: true  },
  { name: "Dumbbell Shoulder Press",    slug: "dumbbell-shoulder-press",    muscleGroups: ["shoulders","triceps"],         equipment: "dumbbell",   isCompound: true  },
  { name: "EZ Bar Curl",                slug: "ez-bar-curl",                muscleGroups: ["biceps"],                      equipment: "barbell",    isCompound: false },
  { name: "Face Pull",                  slug: "face-pull",                  muscleGroups: ["shoulders","back"],            equipment: "cable",      isCompound: false },
  { name: "Floor Press",                slug: "floor-press",                muscleGroups: ["chest","triceps"],             equipment: "barbell",    isCompound: true  },
  { name: "Front Raise",                slug: "front-raise",                muscleGroups: ["shoulders"],                   equipment: "dumbbell",   isCompound: false },
  { name: "Front Squat",                slug: "front-squat",                muscleGroups: ["quads","glutes"],              equipment: "barbell",    isCompound: true  },
  { name: "Glute Bridge",               slug: "glute-bridge",               muscleGroups: ["glutes","hamstrings"],         equipment: "bodyweight", isCompound: false },
  { name: "Goblet Squat",               slug: "goblet-squat",               muscleGroups: ["quads","glutes"],              equipment: "dumbbell",   isCompound: true  },
  { name: "Good Morning",               slug: "good-morning",               muscleGroups: ["hamstrings","back"],           equipment: "barbell",    isCompound: true  },
  { name: "Hack Squat",                 slug: "hack-squat",                 muscleGroups: ["quads","glutes"],              equipment: "machine",    isCompound: true  },
  { name: "Hammer Curl",                slug: "hammer-curl",                muscleGroups: ["biceps"],                      equipment: "dumbbell",   isCompound: false },
  { name: "Hanging Leg Raise",          slug: "hanging-leg-raise",          muscleGroups: ["core"],                        equipment: "bodyweight", isCompound: false },
  { name: "Hip Thrust",                 slug: "hip-thrust",                 muscleGroups: ["glutes","hamstrings"],         equipment: "barbell",    isCompound: true  },
  { name: "Incline Bench Press",        slug: "incline-bench-press",        muscleGroups: ["chest","triceps","shoulders"], equipment: "barbell",    isCompound: true  },
  { name: "Incline Dumbbell Press",     slug: "incline-dumbbell-press",     muscleGroups: ["chest","triceps","shoulders"], equipment: "dumbbell",   isCompound: true  },
  { name: "Incline Fly",                slug: "incline-fly",                muscleGroups: ["chest"],                       equipment: "dumbbell",   isCompound: false },
  { name: "Jump Rope",                  slug: "jump-rope",                  muscleGroups: ["cardio"],                      equipment: "bodyweight", isCompound: false },
  { name: "Kettlebell Swing",           slug: "kettlebell-swing",           muscleGroups: ["glutes","hamstrings","back"],  equipment: "dumbbell",   isCompound: true  },
  { name: "Lat Pulldown",               slug: "lat-pulldown",               muscleGroups: ["back","biceps"],               equipment: "cable",      isCompound: true  },
  { name: "Lateral Raise",              slug: "lateral-raise",              muscleGroups: ["shoulders"],                   equipment: "dumbbell",   isCompound: false },
  { name: "Leg Curl",                   slug: "leg-curl",                   muscleGroups: ["hamstrings"],                  equipment: "machine",    isCompound: false },
  { name: "Leg Extension",              slug: "leg-extension",              muscleGroups: ["quads"],                       equipment: "machine",    isCompound: false },
  { name: "Leg Press",                  slug: "leg-press",                  muscleGroups: ["quads","glutes"],              equipment: "machine",    isCompound: true  },
  { name: "Lunges",                     slug: "lunges",                     muscleGroups: ["quads","glutes","hamstrings"], equipment: "dumbbell",   isCompound: true  },
  { name: "Muscle-up",                  slug: "muscle-up",                  muscleGroups: ["back","chest","triceps"],      equipment: "bodyweight", isCompound: true  },
  { name: "Overhead Press",             slug: "overhead-press",             muscleGroups: ["shoulders","triceps"],         equipment: "barbell",    isCompound: true  },
  { name: "Overhead Tricep Extension",  slug: "overhead-tricep-extension",  muscleGroups: ["triceps"],                     equipment: "dumbbell",   isCompound: false },
  { name: "Pec Deck",                   slug: "pec-deck",                   muscleGroups: ["chest"],                       equipment: "machine",    isCompound: false },
  { name: "Pendlay Row",                slug: "pendlay-row",                muscleGroups: ["back","biceps"],               equipment: "barbell",    isCompound: true  },
  { name: "Plank",                      slug: "plank",                      muscleGroups: ["core"],                        equipment: "bodyweight", isCompound: false },
  { name: "Preacher Curl",              slug: "preacher-curl",              muscleGroups: ["biceps"],                      equipment: "barbell",    isCompound: false },
  { name: "Pull-up",                    slug: "pull-up",                    muscleGroups: ["back","biceps"],               equipment: "bodyweight", isCompound: true  },
  { name: "Push-up",                    slug: "push-up",                    muscleGroups: ["chest","triceps","shoulders"], equipment: "bodyweight", isCompound: true  },
  { name: "Rear Delt Fly",              slug: "rear-delt-fly",              muscleGroups: ["shoulders","back"],            equipment: "dumbbell",   isCompound: false },
  { name: "Romanian Deadlift",          slug: "romanian-deadlift",          muscleGroups: ["hamstrings","glutes","back"],  equipment: "barbell",    isCompound: true  },
  { name: "Rowing Erg",                 slug: "rowing-erg",                 muscleGroups: ["cardio","back"],               equipment: "machine",    isCompound: false },
  { name: "Russian Twist",              slug: "russian-twist",              muscleGroups: ["core"],                        equipment: "bodyweight", isCompound: false },
  { name: "Seated Cable Row",           slug: "seated-cable-row",           muscleGroups: ["back","biceps"],               equipment: "cable",      isCompound: true  },
  { name: "Seated Calf Raise",          slug: "seated-calf-raise",          muscleGroups: ["calves"],                      equipment: "machine",    isCompound: false },
  { name: "Skull Crusher",              slug: "skull-crusher",              muscleGroups: ["triceps"],                     equipment: "barbell",    isCompound: false },
  { name: "Squat",                      slug: "squat",                      muscleGroups: ["quads","glutes","hamstrings"], equipment: "barbell",    isCompound: true  },
  { name: "Standing Calf Raise",        slug: "standing-calf-raise",        muscleGroups: ["calves"],                      equipment: "bodyweight", isCompound: false },
  { name: "Stationary Bike",            slug: "stationary-bike",            muscleGroups: ["cardio"],                      equipment: "machine",    isCompound: false },
  { name: "Step-up",                    slug: "step-up",                    muscleGroups: ["quads","glutes"],              equipment: "dumbbell",   isCompound: true  },
  { name: "Stiff-Leg Deadlift",         slug: "stiff-leg-deadlift",         muscleGroups: ["hamstrings","glutes"],         equipment: "barbell",    isCompound: true  },
  { name: "Sumo Deadlift",              slug: "sumo-deadlift",              muscleGroups: ["glutes","hamstrings","back"],  equipment: "barbell",    isCompound: true  },
  { name: "Superman",                   slug: "superman",                   muscleGroups: ["back","core"],                 equipment: "bodyweight", isCompound: false },
  { name: "T-Bar Row",                  slug: "t-bar-row",                  muscleGroups: ["back","biceps"],               equipment: "barbell",    isCompound: true  },
  { name: "Treadmill Run",              slug: "treadmill-run",              muscleGroups: ["cardio"],                      equipment: "machine",    isCompound: false },
  { name: "Tricep Pushdown",            slug: "tricep-pushdown",            muscleGroups: ["triceps"],                     equipment: "cable",      isCompound: false },
  { name: "Upright Row",                slug: "upright-row",                muscleGroups: ["shoulders","traps"],           equipment: "barbell",    isCompound: false },
  { name: "Wide Grip Pull-up",          slug: "wide-grip-pull-up",          muscleGroups: ["back","biceps"],               equipment: "bodyweight", isCompound: true  },
  { name: "Wrist Curl",                 slug: "wrist-curl",                 muscleGroups: ["arms"],                        equipment: "barbell",    isCompound: false },
  { name: "Zercher Squat",              slug: "zercher-squat",              muscleGroups: ["quads","glutes","back"],       equipment: "barbell",    isCompound: true  },
];

async function seed() {
  console.log(`Seeding ${exercises.length} exercises...`);
  await db
    .insert(exerciseLibrary)
    .values(exercises.map(e => ({ ...e, isCustom: false })))
    .onConflictDoNothing(); // idempotent — safe to re-run
  console.log("Done.");
  process.exit(0);
}

seed().catch((err) => { console.error(err); process.exit(1); });
